replicaCount: 1

image:
  repository: ghcr.io/erauner12/mergeable
  pullPolicy: Always
  # Tag is overridden by CI before publishing the Helm Chart.
  tag: "0db5786-20250603193208"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

env:
  MERGEABLE_GITHUB_URLS: "https://api.github.com,https://github.medallia.com/api/v3"
  MERGEABLE_EXTENDED_SEARCH: ""

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # This is an extremely small container running base nginx, resource requests are minimal.
  # requests:
  #   cpu: 50m
  #   memory: 64Mi

volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

autoscaling:
  enabled: false
