name: Release

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write
  id-token: write 

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      GHCR_OWNER: erauner12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.5.0
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build assets
        run: pnpm install && pnpm build
        env:
          VITE_COMMIT_SHA: ${{ github.sha }}
      - name: Tag image
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ env.GHCR_OWNER }}/mergeable
          tags: |
            type=raw,value=${{ github.sha }}
            type=raw,value=latest
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: apps/web
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VITE_COMMIT_SHA=${{ github.sha }}
      - name: Sign image
        env:
          COSIGN_EXPERIMENTAL: "1" # Required for keyless signing
        run: |
          cosign sign --yes ghcr.io/${{ env.GHCR_OWNER }}/mergeable:${{ github.sha }}
          cosign sign --yes ghcr.io/${{ env.GHCR_OWNER }}/mergeable:latest
  helm:
    runs-on: ubuntu-latest
    needs: [docker]
    env:
      GHCR_OWNER: erauner12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Update image tag in values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: helm/mergeable/values.yaml
          propertyPath: image.tag
          value: ${{ github.sha }}
          commitChange: false
      - name: Package chart
        run: helm package helm/mergeable --version 0.0.${{ github.run_number }} --app-version ${{ github.sha }} --destination dist
      - name: Push chart
        run: helm push dist/*.tgz oci://ghcr.io/${{ env.GHCR_OWNER }}/helm